services:
  - docker

env:
  global:
    - PDBSERVER="http://192.168.0.1:7474"
    - PDBuser="neo4j"
    - PDBpassword="neo4j"

before_install:
  - travis_wait 200 docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 dockernet
  - travis_wait 200 docker run -d --name db -p 7474:7474 --net=dockernet --env=NEO4J_AUTH=${PDBuser}/${PDBpassword} --env=NEOREADONLY=false --env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes --volume=$HOME/neo4j/data:/data virtualflybrain/docker-vfb-neo4j-productiondb
  - sleep 30s

script:
  - docker logs db
  - curl -u ${PDBuser}:${PDBpassword} "http://localhost:7474/db/data/"
  - docker build -t test-image:test .
  - travis_wait 200 docker run -d --name test --net=dockernet --env=VFB_OWL_VERSION=dev --env=PDBSERVER=${PDBSERVER} --env=PDBuser=${PDBuser} --env=PDBpassword=${PDBpassword} test-image:test
  - sleep 2m
  - docker logs test 
  - if docker logs test 2>&1 | grep -q Error; then exit 1; fi
  - sleep 5m
  - docker logs --since 6m test  
  - if docker logs test 2>&1 | grep -q Error; then exit 1; fi
  - sleep 5m
  - docker logs --since 6m test  
  - if docker logs test 2>&1 | grep -q Error; then exit 1; fi
  - sleep 5m
  - docker logs --since 6m test  
  - if docker logs test 2>&1 | grep -q Error; then exit 1; fi
  - sleep 5m
  - docker logs --since 6m test  
  - if docker logs test 2>&1 | grep -q Error; then exit 1; fi
  - sleep 5m
  - docker logs --since 6m test  
  - if docker logs test 2>&1 | grep -q Error; then exit 1; fi
